@MIPSDK_FileOperations_API_HostAddress = http://localhost:5161
@BearerToken = <access-token>
@InputFilePath = D:\WorkDocs\MIP_SDK_Tests\MIPSDK_UDP_Test\MIPSDK_TestDoc.pdf
@OutputFilePath = D:\\WorkDocs\\MIP_SDK_Tests\\MIPSDK_UDP_Test\\ProtectedFiles
@OutputFileName = MIPSDK_TestDoc_Protected.pdf

### Health Check Endpoint
GET {{MIPSDK_FileOperations_API_HostAddress}}/api/healthcheck/status
Accept: application/json

### Protect File Endpoint
POST {{MIPSDK_FileOperations_API_HostAddress}}/api/fileprotection/protect
Authorization: Bearer {{BearerToken}}
Content-Type: multipart/form-data; boundary=----FormBoundary

------FormBoundary
Content-Disposition: form-data; name="file"; filename="MIPSDK_TestDoc.pdf"
Content-Type: application/pdf

<{{InputFilePath}}
------FormBoundary
Content-Disposition: form-data; name="protectionDefinition"
Content-Type: application/json

{
  "userPermissions": [
    {
      "email": "humpty@soumiorg.onmicrosoft.com",
      "rights": ["VIEW"]
    },
    {
      "email": "dumpty@soumiorg.onmicrosoft.com",
      "rights": ["PRINT"]
    }
  ],
  "includeCallerAsOwner": true,
  "outputFileName": "{{OutputFileName}}",
  "outputFolderPath": "{{OutputFilePath}}"
}
------FormBoundary--